"""Website-embed widget config — normalization, public view, CSP + snippet.

An agent can be embedded as a chat widget on any external website. All of the
per-agent knobs (on/off, allowed domains, colours, greeting …) live in the
agent's ``metadata['embed']`` blob — no schema migration, same lane as
``llm_config`` / ``chat_ui`` (see app/api/agents.py update_agent).

This module is the single source of truth for that blob's shape. It is imported
by BOTH the API router (to persist owner edits + serve the public config) and
app/main.py (to serve the standalone /embed/<agent_id> page with the right
Content-Security-Policy frame-ancestors and to build the copy-paste snippet), so
it must stay dependency-free (no DB, no FastAPI).
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Dict, List, Optional
from urllib.parse import urlsplit

# Display defaults — used to fill a public config so the standalone page always
# has something sane to render even before the owner customises anything.
_DEFAULTS: Dict[str, Any] = {
    "enabled": False,
    "allowed_domains": [],
    "accent": "#4f46e5",
    "title": "Chat with us",
    "subtitle": "",
    "greeting": "Hi! How can I help you today?",
    "placeholder": "Type your message…",
    "launcher_position": "right",   # "right" | "left"
}

_HEX_RE = re.compile(r"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$")
# A registrable host with optional port. We deliberately accept a bare host
# ("example.com", "app.acme.io:8080") — the owner pastes domains, not URLs.
_HOST_RE = re.compile(r"^[a-zA-Z0-9.-]+(?::\d{1,5})?$")
_CHAT_UI_CONFIG_PATH = Path(__file__).resolve().parents[2] / "data" / "config" / "chat_ui.json"
_EMBED_ICONS_PATH = Path(__file__).resolve().parents[2] / "data" / "config" / "embed_icons.json"

# Launcher icon fallback — a classic chat bubble, used when an agent has no
# icon configured or the name isn't in the curated set. Generated by
# scripts/gen_embed_icons.cjs (see data/config/embed_icons.json).
_CHAT_BUBBLE_SVG = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" '
    'stroke="currentColor" stroke-width="2" stroke-linecap="round" '
    'stroke-linejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 '
    '8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1'
    '-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 '
    '1 8 8v.5z"/></svg>'
)

_EMBED_ICONS: Optional[Dict[str, str]] = None


def _embed_icons() -> Dict[str, str]:
    """Curated icon-name → SVG-markup map (lazy, cached)."""
    global _EMBED_ICONS
    if _EMBED_ICONS is None:
        try:
            _EMBED_ICONS = json.loads(_EMBED_ICONS_PATH.read_text(encoding="utf-8"))
        except Exception:
            _EMBED_ICONS = {}
    return _EMBED_ICONS


def agent_icon_svg(name: Optional[str]) -> str:
    """SVG markup for an agent's configured icon (chat-bubble fallback)."""
    icons = _embed_icons()
    key = (name or "").strip().lower()
    return icons.get(key) or _CHAT_BUBBLE_SVG


def _merge_chat_profile(base: Any, overrides: Any) -> Dict[str, Any]:
    """Deep-merge a surface profile over chat_common without mutating either.

    Objects inherit key-by-key; lists intentionally replace the common list so a
    surface can choose its own visible controls or layout order.
    """
    out = dict(base) if isinstance(base, dict) else {}
    if not isinstance(overrides, dict):
        return out
    for key, value in overrides.items():
        if isinstance(value, dict):
            out[key] = _merge_chat_profile(out.get(key), value)
        else:
            out[key] = value
    return out


def embed_chat_ui_config() -> Dict[str, Any]:
    """Return the public embedded-chat UI profile.

    The profiles live beside the main chat footer controls so the app panel,
    standalone iframe, and host-page launcher can be tuned from one JSON file.
    They contain styling only and are safe to publish to anonymous visitors.
    """
    try:
        raw = json.loads(_CHAT_UI_CONFIG_PATH.read_text(encoding="utf-8"))
        if not isinstance(raw, dict):
            return {}
        # The widget is one peer surface: inherit its baseline from chat_common
        # while retaining its own launcher, messages, and visual overrides.
        return _merge_chat_profile(raw.get("chat_common"), raw.get("chat_widget"))
    except (OSError, ValueError, TypeError):
        return {}


def widget_presentation_defaults() -> Dict[str, Any]:
    """Map the global widget presentation block onto the per-agent embed shape."""
    widget = embed_chat_ui_config()
    messages = widget.get("messages") if isinstance(widget.get("messages"), dict) else {}
    launcher = widget.get("launcher") if isinstance(widget.get("launcher"), dict) else {}
    return {
        **_DEFAULTS,
        "accent": launcher.get("accent", _DEFAULTS["accent"]),
        "title": messages.get("title", _DEFAULTS["title"]),
        "subtitle": messages.get("subtitle", _DEFAULTS["subtitle"]),
        "greeting": messages.get("greeting", _DEFAULTS["greeting"]),
        "placeholder": messages.get("pill_placeholder", _DEFAULTS["placeholder"]),
        "launcher_position": launcher.get("position", _DEFAULTS["launcher_position"]),
    }


def _clean_domain(raw: str) -> Optional[str]:
    """Reduce whatever the owner pasted to a bare ``host[:port]`` (or None).

    Tolerant on input (full URL, trailing slash, scheme, leading ``*.``) so the
    config UI can stay simple, strict on output so it's safe to drop straight
    into a CSP ``frame-ancestors`` list."""
    s = (raw or "").strip().lower()
    if not s:
        return None
    # Strip a scheme + path if they pasted a full URL.
    if "//" in s:
        s = urlsplit(s if "://" in s else "http://" + s).netloc or s
    s = s.split("/")[0].strip()
    s = s.lstrip("*.")  # wildcard subdomain → registrable host (CSP host-source covers subdomains via the leading *. we re-add in the CSP builder)
    if not s or not _HOST_RE.match(s):
        return None
    return s


def normalize_embed_config(
    patch: Dict[str, Any], existing: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """Shallow-merge ``patch`` onto ``existing`` and coerce every field to a safe,
    typed value. Unknown keys are dropped. Returns the blob to persist."""
    out: Dict[str, Any] = dict(existing or {})
    p = patch or {}

    if "enabled" in p:
        out["enabled"] = bool(p["enabled"])

    if "allowed_domains" in p:
        raw = p["allowed_domains"]
        if isinstance(raw, str):
            raw = re.split(r"[\s,]+", raw)
        cleaned: List[str] = []
        for d in (raw or []):
            c = _clean_domain(str(d))
            if c and c not in cleaned:
                cleaned.append(c)
        out["allowed_domains"] = cleaned[:50]  # generous cap; guards a runaway CSP header

    if "accent" in p:
        a = str(p["accent"] or "").strip()
        out["accent"] = a if _HEX_RE.match(a) else _DEFAULTS["accent"]

    for key in ("title", "subtitle", "greeting", "placeholder"):
        if key in p:
            # Trim + hard length cap so a stray paste can't bloat the page/header.
            out[key] = str(p[key] or "").strip()[:400]

    if "launcher_position" in p:
        pos = str(p["launcher_position"] or "").strip().lower()
        out["launcher_position"] = pos if pos in ("right", "left") else "right"

    return out


def read_embed_config(agent: Optional[dict]) -> Dict[str, Any]:
    """Pull the raw stored embed blob out of an agent row's metadata (or {})."""
    if not agent:
        return {}
    meta = agent.get("metadata")
    if isinstance(meta, str):
        try:
            meta = json.loads(meta)
        except Exception:
            meta = {}
    if not isinstance(meta, dict):
        return {}
    blob = meta.get("embed")
    return blob if isinstance(blob, dict) else {}


def public_embed_config(agent: Optional[dict]) -> Dict[str, Any]:
    """Display-safe config for the standalone page / loader, defaults filled in.

    Everything in the embed blob is presentation-only (no secrets), so this is
    just defaults ⊕ stored values — safe to serve unauthenticated. The agent's
    per-agent ``metadata.chat_ui`` is deep-merged into the widget chat_ui profile
    so that agent-specific widget customisations (accent, messages, launcher, etc.)
    flow to the embedded page automatically."""
    cfg = widget_presentation_defaults()
    cfg.update(read_embed_config(agent))
    meta = agent.get("metadata") if agent else {}
    if isinstance(meta, str):
        try:
            meta = json.loads(meta)
        except Exception:
            meta = {}
    # The host-page launcher cannot use the authenticated agent endpoint. Send
    # only the presentation-safe Lucide name saved by the Agents page.
    cfg["agent_icon"] = (meta.get("icon") or "bot") if isinstance(meta, dict) else "bot"
    # And the ready-to-inject SVG for that icon, so the launcher renders the
    # agent's configured icon with zero client-side icon-library dependency
    # (chat-bubble fallback for unknown/missing names).
    cfg["agent_icon_svg"] = agent_icon_svg(cfg.get("agent_icon"))
    # Never leak the domain allowlist to the public config — it's an owner-only
    # security setting, enforced server-side via the CSP header, not the client.
    cfg.pop("allowed_domains", None)
    # Build the widget chat_ui profile: start from the global chat_ui.json widget
    # surface (chat_common merged with chat_widget), then layer the agent's per-agent
    # override — first its chat_common keys, then its chat_widget keys — so the
    # embed shows that agent's custom accent/messages/launcher.
    widget_ui = embed_chat_ui_config()
    agent_cu = meta.get("chat_ui") if isinstance(meta, dict) else None
    if isinstance(agent_cu, dict):
        # agent_cu follows the chat_ui.json structure: chat_common + per-surface keys.
        # Merge chat_common first (shared base), then chat_widget (widget-specific).
        agent_common = agent_cu.get("chat_common")
        if isinstance(agent_common, dict):
            widget_ui = _merge_chat_profile(widget_ui, agent_common)
        agent_widget = agent_cu.get("chat_widget")
        if isinstance(agent_widget, dict):
            widget_ui = _merge_chat_profile(widget_ui, agent_widget)
    cfg["chat_ui"] = widget_ui
    return cfg


def embed_frame_ancestors(cfg: Dict[str, Any]) -> str:
    """Build the CSP ``frame-ancestors`` directive value for an agent's page.

    - No domains configured → ``*`` (frictionless: embed anywhere, matching the
      product's "drop it on any site" promise; documented as the open default).
    - Domains configured → ``'self'`` + each host, both bare and as a wildcard
      parent so ``example.com`` also authorises ``www.example.com``. This is the
      owner's opt-in lockdown."""
    domains = cfg.get("allowed_domains") or []
    if not domains:
        return "*"
    sources = ["'self'"]
    for d in domains:
        sources.append(f"https://{d}")
        sources.append(f"https://*.{d}")
    return " ".join(sources)


def build_embed_snippet(origin: str, agent_id: str, cfg: Dict[str, Any]) -> str:
    """The copy-paste ``<script>`` the owner drops into their site's HTML."""
    origin = (origin or "").rstrip("/")
    pos = cfg.get("launcher_position") or "right"
    return (
        f'<script src="{origin}/embed.js" '
        f'data-agent="{agent_id}" '
        f'data-position="{pos}" async></script>'
    )
