"""
Secrets factory: pick a SecretsBackend based on persisted config.

Mode is stored in `secrets_mode.json` alongside `db_mode.json`.

Bootstrap order:
  1. Read `secrets_mode.json` (or env override WEBAGENT_SECRETS_PROVIDER)
  2. Construct the chosen backend lazily — failures fall back to inline_db
  3. The chosen backend's own config (e.g. GCP project ID) comes from env vars
     only, never from the app DB. This prevents a chicken-and-egg.

Available providers:
  - "inline_db"  (default)
  - "env"
  - "os_keyring"
  - "gcp_secret_manager"
  - "aws_secrets_manager"

DROP-IN — to add a vault, drop ONE file in app/secrets/ with a SecretsBackend
subclass (its `name` is the provider id) and a `FEATURE` header. It is
auto-discovered (see `_discovered()`); the explicit `_construct` branches below
are only a safety fallback. Do not edit this file to add one. See CLAUDE.md
("Core vs. plugins") and docs/claude/production-editions.md.
"""

import json
import logging
import os
from typing import Optional

from app.secrets.interface import SecretsBackend

logger = logging.getLogger(__name__)

_AGENT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_MODE_FILE = os.path.join(_AGENT_DIR, "secrets_mode.json")

_AVAILABLE = (
    "inline_db",
    "env",
    "os_keyring",
    "gcp_secret_manager",
    "aws_secrets_manager",
)

_backend: Optional[SecretsBackend] = None
_mode: Optional[str] = None
_discovered_cache: Optional[dict] = None
# The provider the SERVER PROCESS booted with — captured on the first mode
# resolution (which happens at startup, before any UI change). Switching the
# vault live (set_mode) rebuilds the backend immediately, but secrets already
# read into memory at boot are not re-fetched; comparing the live mode against
# this tells the UI when a restart is recommended for a fully clean cutover.
_boot_provider: Optional[str] = None


def _discovered() -> dict:
    """Auto-discovered provider classes ({id: cls}) from any file in this
    package — so a new vault is added by dropping a file, no edit here."""
    global _discovered_cache
    if _discovered_cache is None:
        try:
            from app.features.registry import discover_backends
            _discovered_cache = discover_backends("app.secrets", SecretsBackend, id_attr="name")
        except Exception as e:
            logger.warning("Secrets provider discovery failed: %s", e)
            _discovered_cache = {}
    return _discovered_cache


def _all_providers() -> tuple:
    """Core providers plus any discovered drop-ins (deduped, core first)."""
    seen = list(_AVAILABLE)
    for pid in _discovered():
        if pid not in seen:
            seen.append(pid)
    return tuple(seen)


def _load_saved_mode() -> Optional[str]:
    try:
        if os.path.exists(_MODE_FILE):
            with open(_MODE_FILE, "r") as f:
                return json.load(f).get("provider")
    except Exception as e:
        logger.warning("Failed to load secrets_mode.json: %s", e)
    return None


def _save_mode(provider: str) -> None:
    # Cloud Run / env-locked mode skips file writes.
    if os.environ.get("WEBAGENT_CONFIG_SOURCE", "").lower() == "env":
        return
    try:
        with open(_MODE_FILE, "w") as f:
            json.dump({"provider": provider}, f)
    except Exception as e:
        logger.warning("Failed to save secrets_mode.json: %s", e)


def get_mode() -> str:
    """Get the current secrets provider name."""
    global _mode, _boot_provider
    if _mode is None:
        # Env override wins
        env_choice = os.environ.get("WEBAGENT_SECRETS_PROVIDER", "").strip()
        if env_choice in _all_providers():
            _mode = env_choice
        else:
            _mode = _load_saved_mode() or "inline_db"
    if _boot_provider is None:
        # First resolution in this process == the provider we booted with.
        _boot_provider = _mode
    return _mode


def set_mode(provider: str) -> None:
    """Switch the secrets provider. Persists to disk and resets cached backend."""
    global _backend, _mode
    if provider not in _all_providers():
        raise ValueError(f"Invalid provider '{provider}'. Must be one of {_all_providers()}")
    _mode = provider
    _backend = None
    _save_mode(provider)
    logger.info("Secrets provider switched to '%s'", provider)


def list_providers() -> list:
    return list(_all_providers())


# ── UI-driven connection config (delegates to provider_config) ──────────────
# Thin wrappers so callers use one import surface (app.secrets) and so saving a
# provider's config/token also drops the cached backend if it is the active one.

def get_provider_config(provider: str) -> dict:
    from app.secrets.provider_config import get_provider_config as _g
    return _g(provider)


def set_provider_config(provider: str, cfg: dict) -> None:
    global _backend
    from app.secrets.provider_config import set_provider_config as _s
    _s(provider, cfg)
    if provider == get_mode():
        _backend = None  # rebuild with the new config on next access


def set_provider_token(provider: str, token):
    global _backend
    from app.secrets.provider_config import set_provider_token as _s
    where = _s(provider, token)
    if provider == get_mode():
        _backend = None
    return where


def token_location(provider: str):
    from app.secrets.provider_config import token_location as _t
    return _t(provider)


def construct(provider: str) -> SecretsBackend:
    """Build a given provider's backend (reading its saved config) WITHOUT
    changing the active mode — used by the UI 'Test' button to probe the
    selected provider before activating it."""
    return _construct(provider)


def _construct(provider: str) -> SecretsBackend:
    # Auto-discovery (one class per drop-in file, keyed by `.name`) is the source
    # of truth and already covers every built-in provider — no per-provider import
    # list to maintain here.
    cls = _discovered().get(provider)
    if cls is not None:
        return cls()
    # inline_db is the irreducible default: keep an explicit branch so it can
    # always be constructed even if discovery itself failed (the get_secrets
    # fallback below also depends on it).
    if provider == "inline_db":
        from app.secrets.inline_db_secrets import InlineDBSecrets
        return InlineDBSecrets()
    raise ValueError(f"Unknown provider: {provider}")


def get_secrets() -> SecretsBackend:
    """Get the active secrets backend instance (lazy)."""
    global _backend
    if _backend is None:
        provider = get_mode()
        try:
            _backend = _construct(provider)
            logger.info("Initialized secrets backend: %s", provider)
        except Exception as e:
            logger.warning(
                "Failed to construct secrets backend '%s' (%s); falling back to inline_db",
                provider, e,
            )
            from app.secrets.inline_db_secrets import InlineDBSecrets
            _backend = InlineDBSecrets()
    return _backend


def get_secrets_status() -> dict:
    """For UI: current provider + reachability info + the saved (non-secret)
    connection config per provider and whether/where each provider's token is
    stored. Tokens themselves are NEVER included."""
    try:
        from app.secrets.provider_config import all_provider_configs, token_location
        configs = all_provider_configs()
        token_saved = {p: token_location(p) for p in _all_providers()}
    except Exception as e:
        logger.warning("Failed to load secrets provider configs: %s", e)
        configs, token_saved = {}, {}
    active = get_mode()
    return {
        "provider": active,
        "available": list(_all_providers()),
        "env_locked": os.environ.get("WEBAGENT_CONFIG_SOURCE", "").lower() == "env",
        "configs": configs,
        "token_saved": token_saved,
        # The provider the process booted with + whether the live choice has
        # diverged from it. The UI uses restart_recommended to offer a one-click
        # server restart for a clean cutover after switching vaults.
        "boot_provider": _boot_provider,
        "restart_recommended": bool(_boot_provider and active != _boot_provider),
    }


def mode_configured() -> bool:
    """True if a provider has been explicitly persisted (the mode file exists).

    Absent file = nobody has chosen yet (fresh install) — the signal the
    first-boot security-defaults seeder uses to know it may act.
    """
    return os.path.exists(_MODE_FILE)


def keyring_is_secure() -> bool:
    """True only when the OS keyring resolves to a real, secure backend.

    Used to decide whether the on-by-default encryption seed may fire: on a host
    where `keyring` is missing, resolves to the no-op 'fail' backend, or falls
    back to an insecure plaintext file store, we must NOT auto-enable encryption
    (the keys would be unprotected or unwritable). This is a cheap class check;
    the seeder still does a real write/read round-trip before committing.
    """
    try:
        import keyring
        import keyring.backends.fail as _fail
    except Exception:
        return False
    try:
        kr = keyring.get_keyring()
    except Exception:
        return False
    if isinstance(kr, _fail.Keyring):
        return False
    mod = (type(kr).__module__ or "").lower()
    name = type(kr).__name__.lower()
    # Reject the alt plaintext / null fallbacks (defeat the purpose of a vault).
    if "keyrings.alt" in mod or "plaintext" in name or "null" in name:
        return False
    # A chainer with no usable child backends behaves like the fail backend.
    children = getattr(kr, "backends", None)
    if children is not None and len(list(children)) == 0:
        return False
    return True
