"""Remote scheduler provider registry (DROP-IN — do not edit this file to add one).

Add a provider by dropping ONE file: app/scheduler/providers/<name>.py with a
``BaseRemoteScheduler`` subclass, a module-level ``PROVIDER = {id, display_name,
description, auth_mode, fields, cls}`` dict, and a ``FEATURE`` header. It is
auto-discovered by ``_discover_dropins()`` — no edit here. The three built-ins
below keep their explicit registration; new providers do not. See CLAUDE.md
("Core vs. plugins") and docs/claude/production-editions.md.

Each provider declares:
  - ``id``  — short identifier used in config.
  - ``display_name`` — UI label.
  - ``fields`` — list of {key, label, type, required, secret} describing the
    settings the admin must fill in. Drives the dynamic form in App Config →
    Automation.
  - ``cls`` — concrete ``BaseRemoteScheduler`` subclass.
"""

from __future__ import annotations

from typing import Any, Callable, Dict, List, Optional, Type

from app.scheduler.base import SchedulerBackend


_REGISTRY: List[Dict[str, Any]] = []


def register(
    *,
    id: str,
    display_name: str,
    fields: List[Dict[str, Any]],
    cls: Type[SchedulerBackend],
    description: str = "",
    auth_mode: str = "api_key",
) -> None:
    _REGISTRY.append({
        "id": id,
        "display_name": display_name,
        "description": description,
        "auth_mode": auth_mode,
        "fields": fields,
        "cls": cls,
    })


def list_providers() -> List[Dict[str, Any]]:
    out = []
    for p in _REGISTRY:
        out.append({
            "id": p["id"],
            "display_name": p["display_name"],
            "description": p["description"],
            "auth_mode": p["auth_mode"],
            "fields": p["fields"],
        })
    return out


def get_provider_class(provider_id: str) -> Optional[Type[SchedulerBackend]]:
    for p in _REGISTRY:
        if p["id"] == provider_id:
            return p["cls"]
    return None


def _register_builtin() -> None:
    if _REGISTRY:
        return
    from app.scheduler.providers.google_cloud import GoogleCloudScheduler
    from app.scheduler.providers.cronjob_org import CronJobOrgScheduler
    from app.scheduler.providers.generic_webhook import GenericWebhookScheduler

    register(
        id="google_cloud",
        display_name="Google Cloud Scheduler",
        description="Push each job to Google Cloud Scheduler (cloudscheduler.googleapis.com). Requires a service account JSON with role roles/cloudscheduler.admin.",
        auth_mode="service_account",
        fields=[
            {"key": "project_id", "label": "GCP project ID", "type": "text", "required": True},
            {"key": "location", "label": "Region (e.g. us-central1)", "type": "text", "required": True},
            {"key": "service_account_json", "label": "Service account JSON", "type": "textarea", "required": True, "secret": True},
            {"key": "fire_base_url", "label": "Public base URL for webhook", "type": "text", "required": False},
            {"key": "job_prefix", "label": "Job name prefix", "type": "text", "required": False, "placeholder": "webagent-"},
        ],
        cls=GoogleCloudScheduler,
    )

    register(
        id="cronjob_org",
        display_name="cron-job.org",
        description="Free hosted cron service. Provide an API token from https://console.cron-job.org/ → API settings.",
        auth_mode="api_key",
        fields=[
            {"key": "api_key", "label": "API key", "type": "password", "required": True, "secret": True},
            {"key": "fire_base_url", "label": "Public base URL for webhook (overrides WEBHOOK_BASE_URL)", "type": "text", "required": False},
        ],
        cls=CronJobOrgScheduler,
    )

    register(
        id="generic_webhook",
        display_name="Generic webhook",
        description="Your own scheduler hits a configured upstream URL. WebAgent POSTs each job's metadata; your service triggers the fire webhook on schedule.",
        auth_mode="api_key",
        fields=[
            {"key": "upstream_url", "label": "Your scheduler service URL (POST target)", "type": "text", "required": True},
            {"key": "auth_header", "label": "Authorization header value (optional)", "type": "password", "required": False, "secret": True},
            {"key": "fire_base_url", "label": "Public base URL for webhook (overrides WEBHOOK_BASE_URL)", "type": "text", "required": False},
        ],
        cls=GenericWebhookScheduler,
    )
    _discover_dropins()


def _discover_dropins() -> None:
    """Register any extra provider dropped into this folder.

    A new provider file declares a module-level ``PROVIDER`` dict
    ({id, display_name, description, auth_mode, fields, cls}) and is picked up
    here automatically — no edit to this file. Built-ins above keep their
    explicit registration; a drop-in whose id is already registered is skipped.
    """
    import importlib
    from pathlib import Path
    folder = Path(__file__).resolve().parent
    existing = {p["id"] for p in _REGISTRY}
    for fpath in sorted(folder.iterdir()):
        if fpath.suffix != ".py" or fpath.name.startswith("_"):
            continue
        try:
            mod = importlib.import_module(f"app.scheduler.providers.{fpath.stem}")
            spec = getattr(mod, "PROVIDER", None)
            if not isinstance(spec, dict) or not spec.get("id") or not spec.get("cls"):
                continue
            if spec["id"] in existing:
                continue
            register(
                id=spec["id"],
                display_name=spec.get("display_name", spec["id"]),
                description=spec.get("description", ""),
                auth_mode=spec.get("auth_mode", "api_key"),
                fields=spec.get("fields", []),
                cls=spec["cls"],
            )
            existing.add(spec["id"])
        except Exception:
            continue


_register_builtin()
