"""Payment processor registry (DROP-IN — do not edit this file to add one).

Add a new processor by dropping ONE file: create
plugins/billing/processors/<name>.py with a class implementing the PaymentProcessor
protocol from .base, a module-level ``processor_cls = YourProcessor``, and a
``FEATURE`` header (id/display_name/status). It is auto-discovered and
registered below — no edit here, no import to add. Delete the file to remove it.
See CLAUDE.md ("Core vs. plugins") and docs/claude/production-editions.md.

The rest of the codebase calls get_processor(name) — it never instantiates
processors directly.
"""

from __future__ import annotations

import os
import logging
from typing import Dict, Optional

from plugins.billing.processors.base import PaymentProcessor

logger = logging.getLogger(__name__)

_REGISTRY: Dict[str, PaymentProcessor] = {}


def register(processor: PaymentProcessor) -> None:
    _REGISTRY[processor.name] = processor


def get_processor(name: str) -> Optional[PaymentProcessor]:
    return _REGISTRY.get(name)


def list_processors() -> list:
    return [
        {
            "name": p.name,
            "display_name": p.display_name,
            "configured": p.is_configured(),
            "features": p.supported_features(),
        }
        for p in _REGISTRY.values()
    ]


# ── Register concrete processors (drop-in) ──
# Any file in this folder exposing a module-level `processor_cls` is registered
# automatically — add a processor by dropping a file, no edit here. Each import
# is guarded so a missing SDK (e.g. stripe not installed) just skips that one.
def _discover_and_register() -> None:
    import importlib
    from pathlib import Path
    folder = Path(__file__).resolve().parent
    for fpath in sorted(folder.iterdir()):
        if fpath.suffix != ".py" or fpath.name.startswith("_") or fpath.stem == "base":
            continue
        mod_name = f"plugins.billing.processors.{fpath.stem}"
        try:
            mod = importlib.import_module(mod_name)
            cls = getattr(mod, "processor_cls", None)
            if cls is None:
                continue
            inst = cls()
            register(inst)
        except Exception as e:
            logger.info("Payment processor %s not registered: %s", fpath.stem, e)


_discover_and_register()


__all__ = [
    "PaymentProcessor",
    "get_processor",
    "list_processors",
    "register",
]
