// Build-time extraction script: reads pi-ai's models.generated.js (ESM) and
// emits a Python module (model_windows.py) with every known model's contextWindow.
//
// Usage: node launcher/scripts/build_model_windows.mjs
//
// You MUST have @earendil-works/pi-ai installed in node_modules for the import to work.

import { fileURLToPath } from "url";
import path from "path";
import fs from "fs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Resolve pi-ai's models module — try global install, then project-local
const piAiPaths = [
  path.resolve(__dirname, "../../node_modules/@earendil-works/pi-ai/dist/models.generated.js"),
  path.resolve("C:/Users/Alex R/AppData/Roaming/npm/node_modules/@earendil-works/pi-ai/dist/models.generated.js"),
];

let MODELS;
for (const p of piAiPaths) {
  if (fs.existsSync(p)) {
    try {
      const url = "file:///" + p.replace(/\\/g, "/").replace(/^\/?/, "");
      const mod = await import(url);
      MODELS = mod.MODELS;
      console.error(`Loaded models from: ${p}`);
      break;
    } catch (e) {
      console.error(`Failed to load ${p}: ${e.message}`);
    }
  }
}

if (!MODELS) {
  console.error("Could not load @earendil-works/pi-ai models. Is it installed?");
  process.exit(1);
}

// Collect all entries
const entries = [];
const byId = new Map();

for (const [provider, models] of Object.entries(MODELS)) {
  for (const [id, m] of Object.entries(models)) {
    const cw = m.contextWindow ?? 128000;
    entries.push({ id, name: m.name ?? id, cw, provider });
    byId.set(id, cw);
  }
}

// Sort longest-id-first for substring matching specificity
entries.sort((a, b) => b.id.length - a.id.length || b.cw - a.cw);

// ── Generate the Python module ──────────────────────────────────────────────
const pyPath = path.resolve(__dirname, "../webagent_launcher/model_windows.py");

const modelCount = entries.length;
const lines = [
  "# Auto-generated by build_model_windows.mjs from @earendil-works/pi-ai",
  "# Do not edit manually. Re-run the build script when pi-ai is updated.",
  `# Source: @earendil-works/pi-ai (pi-ai), ${modelCount} models`,
  "",
  "# Maps model-id substrings to context window sizes.",
  '# Substring matching (longest first) so a query for "gpt-4.1-nano"',
  '# matches the most specific entry before falling back to "gpt-4.1".',
  "from typing import List, Tuple",
  "",
  "MODEL_CONTEXT_WINDOWS: List[Tuple[str, int]] = [",
];

for (const e of entries) {
  lines.push(`    ("${e.id}", ${e.cw}),`);
}

lines.push("]");
lines.push("");
lines.push("# Quick lookup by full model ID (dict form, higher priority than substring list)");
lines.push("MODEL_CONTEXT_BY_ID: dict[str, int] = {");
for (const [id, cw] of byId) {
  lines.push(`    "${id}": ${cw},`);
}
lines.push("}");
lines.push("");

fs.writeFileSync(pyPath, lines.join("\n") + "\n");
console.error(`Wrote ${pyPath} (${modelCount} entries)`);
