"""Deploy-target registry (DROP-IN — do not edit this file to add a cloud).

Add a target by dropping ONE file into ``app/deploy/providers/<id>.py`` exposing
a module-level ``PROVIDER`` (a ``BaseDeployProvider`` instance) and a ``FEATURE``
header. ``_discover()`` imports every non-underscore file in that folder and
registers any that expose a valid ``PROVIDER`` — no edit here, no central
if/elif. Mirrors app/scheduler/providers/__init__.py.
"""

from __future__ import annotations

import importlib
import logging
from pathlib import Path
from typing import Dict, List, Optional

from app.deploy.base import BaseDeployProvider

logger = logging.getLogger(__name__)

_REGISTRY: Dict[str, BaseDeployProvider] = {}
_ORDER: List[str] = []
_loaded = False


def _discover() -> None:
    global _loaded
    if _loaded:
        return
    _loaded = True
    folder = Path(__file__).resolve().parent / "providers"
    for fpath in sorted(folder.iterdir()):
        if fpath.suffix != ".py" or fpath.name.startswith("_"):
            continue
        try:
            mod = importlib.import_module(f"app.deploy.providers.{fpath.stem}")
            provider = getattr(mod, "PROVIDER", None)
            if not isinstance(provider, BaseDeployProvider) or not provider.id:
                continue
            if provider.id in _REGISTRY:
                continue
            _REGISTRY[provider.id] = provider
            _ORDER.append(provider.id)
        except Exception as e:
            logger.warning("deploy provider %s failed to load: %s", fpath.stem, e)


def list_providers() -> List[BaseDeployProvider]:
    _discover()
    return [_REGISTRY[i] for i in _ORDER]


def get_provider(provider_id: str) -> Optional[BaseDeployProvider]:
    _discover()
    return _REGISTRY.get(provider_id)
